/**
 * 知视 KnowledgeView - Main World 脚本
 *
 * 此脚本运行在页面的 MAIN world，可以直接访问 YouTube 的 JS 对象。
 * 负责通过 YouTube 播放器 API 获取字幕轨道信息，以及控制视频跳转。
 * 与 content script（ISOLATED world）通过 window.postMessage 通信。
 */

(function () {
  'use strict';

  // ============ 消息监听 ============

  /**
   * 监听来自 content script 的消息
   * content script 通过 window.postMessage 发送消息，main-world.js 在此接收
   */
  window.addEventListener('message', function (event) {
    // 安全检查：只接受来自同一窗口的消息
    if (event.source !== window) return;

    var message = event.data;
    if (!message || !message.type) return;

    // 只处理 KV_ 前缀的消息
    if (message.type.indexOf('KV_') !== 0) return;

    console.log('[知视 Main World] 收到消息:', message.type);

    switch (message.type) {
      case 'KV_GET_CAPTION_TRACKS':
        handleGetCaptionTracks();
        break;
      case 'KV_FETCH_CAPTION_SUBTITLES':
        handleFetchCaptionSubtitles(message);
        break;
      case 'KV_SEEK_VIDEO':
        handleSeekVideo(message.time);
        break;
      default:
        // 未知消息类型，忽略
        break;
    }
  });

  // ============ 播放器获取 ============

  /**
   * 获取 YouTube 播放器元素
   * @returns {HTMLElement|null} 播放器DOM元素
   */
  function getPlayerElement() {
    // YouTube 播放器的标准 ID
    var player = document.getElementById('movie_player');
    if (player) {
      return player;
    }
    // 备选：通过 ytd-player 标签查找
    var ytdPlayer = document.querySelector('ytd-player');
    if (ytdPlayer) {
      var innerPlayer = ytdPlayer.querySelector('#movie_player');
      if (innerPlayer) {
        return innerPlayer;
      }
    }
    return null;
  }

  /**
   * 获取 YouTube 播放器响应数据（playerResponse）
   * 尝试多种方式获取，增加兼容性
   * @returns {Object|null} 播放器响应对象
   */
  function getPlayerResponse() {
    // 方式1：通过 movie_player 元素的 getPlayerResponse() 方法
    var playerEl = getPlayerElement();
    if (playerEl && typeof playerEl.getPlayerResponse === 'function') {
      try {
        var response = playerEl.getPlayerResponse();
        if (response && response.captions) {
          return response;
        }
      } catch (e) {
        console.warn('[知视 Main World] getPlayerResponse() 调用失败:', e);
      }
    }

    // 方式2：通过 ytplayer.config 获取
    try {
      if (window.ytplayer && window.ytplayer.config && window.ytplayer.config.args) {
        var args = window.ytplayer.config.args;
        // 新版 YouTube 可能将数据放在 raw_player_response 中
        if (args.raw_player_response) {
          return args.raw_player_response;
        }
        // 旧版可能直接有 player_response 字段（JSON字符串）
        if (args.player_response && typeof args.player_response === 'string') {
          return JSON.parse(args.player_response);
        }
        if (args.player_response && typeof args.player_response === 'object') {
          return args.player_response;
        }
      }
    } catch (e) {
      console.warn('[知视 Main World] ytplayer.config 获取失败:', e);
    }

    // 方式3：通过全局变量 ytInitialPlayerResponse 获取（页面初始加载时可用）
    try {
      if (window.ytInitialPlayerResponse && window.ytInitialPlayerResponse.captions) {
        return window.ytInitialPlayerResponse;
      }
    } catch (e) {
      console.warn('[知视 Main World] ytInitialPlayerResponse 获取失败:', e);
    }

    return null;
  }

  // ============ 字幕轨道获取 ============

  /**
   * 从播放器响应中提取字幕轨道列表
   * @returns {Array} 字幕轨道数组
   */
  function extractCaptionTracks(playerResponse) {
    if (!playerResponse || !playerResponse.captions) {
      return [];
    }

    var captionsRenderer = playerResponse.captions.playerCaptionsTracklistRenderer;
    if (!captionsRenderer) {
      return [];
    }

    var captionTracks = captionsRenderer.captionTracks;
    if (!captionTracks || !Array.isArray(captionTracks)) {
      return [];
    }

    // 提取每个轨道的关键信息
    return captionTracks.map(function (track) {
      // 提取语言名称，优先使用 simpleText
      var trackName = '';
      if (track.name) {
        if (track.name.simpleText) {
          trackName = track.name.simpleText;
        } else if (track.name.runs && track.name.runs.length > 0) {
          trackName = track.name.runs[0].text;
        }
      }
      // 如果没有名称，使用语言代码作为后备
      if (!trackName) {
        trackName = track.languageCode || '未知语言';
      }

      return {
        baseUrl: track.baseUrl || '',
        languageCode: track.languageCode || '',
        name: trackName,
        kind: track.kind || '',
        // kind 为 'asr' 表示自动生成
        isAutoGenerated: track.kind === 'asr',
        vssId: track.vssId || ''
      };
    });
  }

  /**
   * 处理获取字幕轨道的请求
   * 获取轨道信息后通过 postMessage 返回结果
   */
  function waitForCaptionTracks(maxAttempts) {
    var attempts = 0;

    return new Promise(function (resolve, reject) {
      function check() {
        attempts++;
        var playerResponse = getPlayerResponse();
        var tracks = extractCaptionTracks(playerResponse);
        if (tracks.length > 0) {
          resolve(tracks);
          return;
        }

        if (attempts >= maxAttempts) {
          if (!playerResponse) {
            reject(new Error('无法获取播放器字幕信息，请等待视频加载完成后重试'));
          } else {
            reject(new Error('该视频暂未提供可读取的字幕轨道，请确认 CC 字幕已加载'));
          }
          return;
        }

        setTimeout(check, 500);
      }

      check();
    });
  }

  function handleGetCaptionTracks() {
    waitForCaptionTracks(60).then(function (tracks) {
      console.log('[知视 Main World] 获取到字幕轨道:', tracks.length, '个');
      window.postMessage({
        type: 'KV_CAPTION_TRACKS_RESULT',
        tracks: tracks,
        error: null
      }, '*');
    }).catch(function (err) {
      console.error('[知视 Main World] 获取字幕轨道失败:', err);
      window.postMessage({
        type: 'KV_CAPTION_TRACKS_RESULT',
        tracks: [],
        error: err.message || '获取字幕轨道失败'
      }, '*');
    });
  }

  // ============ 视频跳转 ============

  /**
   * 处理视频跳转请求
   * 调用 YouTube 播放器 API 跳转到指定时间
   * @param {number} time - 跳转时间（秒）
   */
  /**
   * 为字幕地址补充 fmt=json3 参数
   * @param {string} baseUrl
   * @returns {string}
   */
  function buildCaptionRequestUrl(baseUrl) {
    if (!baseUrl) {
      return '';
    }

    try {
      var url = new URL(baseUrl, window.location.href);
      if (!url.searchParams.has('fmt')) {
        url.searchParams.set('fmt', 'json3');
      }
      return url.toString();
    } catch (e) {
      if (baseUrl.indexOf('fmt=') === -1) {
        return baseUrl + (baseUrl.indexOf('?') !== -1 ? '&' : '?') + 'fmt=json3';
      }
      return baseUrl;
    }
  }

  /**
   * 构建多个字幕格式地址，兼容不同 YouTube 字幕接口返回格式。
   * @param {string} baseUrl
   * @returns {Array<string>}
   */
  function buildCaptionRequestUrls(baseUrl) {
    if (!baseUrl) {
      return [];
    }

    try {
      var formats = ['json3', 'vtt', 'srv3', ''];
      var urls = [];
      for (var formatIndex = 0; formatIndex < formats.length; formatIndex++) {
        var url = new URL(baseUrl, window.location.href);
        if (formats[formatIndex]) {
          url.searchParams.set('fmt', formats[formatIndex]);
        } else {
          url.searchParams.delete('fmt');
        }
        var value = url.toString();
        if (urls.indexOf(value) === -1) {
          urls.push(value);
        }
      }
      return urls;
    } catch (error) {
      return [buildCaptionRequestUrl(baseUrl)];
    }
  }

  /**
   * 判断字幕接口响应是否包含可解析的字幕结构。
   * @param {string} text
   * @returns {boolean}
   */
  function looksLikeCaptionText(text) {
    var normalized = String(text || '').trim();
    if (!normalized) {
      return false;
    }

    if (/^WEBVTT/i.test(normalized) || normalized.indexOf('-->') !== -1) {
      return true;
    }

    if (/^</.test(normalized) && /<(?:text|p)\b/i.test(normalized)) {
      return true;
    }

    try {
      var parsed = JSON.parse(normalized);
      if (!parsed || !Array.isArray(parsed.events)) {
        return false;
      }
      return parsed.events.some(function (event) {
        return event && Array.isArray(event.segs) && event.segs.length > 0;
      });
    } catch (error) {
      return false;
    }
  }

  /**
   * 向 content script 返回字幕请求结果
   * @param {Object} payload
   */
  function postCaptionSubtitlesResult(payload) {
    window.postMessage({
      type: 'KV_CAPTION_SUBTITLES_RESULT',
      requestId: payload.requestId || '',
      text: payload.text || '',
      url: payload.url || '',
      status: typeof payload.status === 'number' ? payload.status : 0,
      contentType: payload.contentType || '',
      error: payload.error || null
    }, '*');
  }

  /**
   * 处理字幕内容请求
   * @param {Object} message
   */
  function handleFetchCaptionSubtitles(message) {
    var requestId = message && message.requestId ? String(message.requestId) : '';
    var track = message && message.track ? message.track : null;

    try {
      if (!track || !track.baseUrl) {
        throw new Error('字幕轨道缺少请求地址');
      }

      var urls = buildCaptionRequestUrls(track.baseUrl);
      if (urls.length === 0) {
        throw new Error('无法生成字幕请求地址');
      }

      function requestNext(index, lastError) {
        if (index >= urls.length) {
          throw lastError || new Error('字幕接口返回了空内容');
        }

        var url = urls[index];
        return fetch(url, {
          method: 'GET',
          credentials: 'include',
          cache: 'no-store'
        }).then(function (resp) {
          var status = resp.status;
          var contentType = resp.headers.get('content-type') || '';
          var finalUrl = resp.url || url;

          if (!resp.ok) {
            throw new Error('字幕请求失败（HTTP ' + status + '）：' + (resp.statusText || '未知错误'));
          }

          return resp.text().then(function (text) {
            if (!looksLikeCaptionText(text)) {
              throw new Error('字幕接口返回了空内容');
            }

            postCaptionSubtitlesResult({
              requestId: requestId,
              text: text,
              url: finalUrl,
              status: status,
              contentType: contentType,
              error: null
            });
          });
        }).catch(function (error) {
          return requestNext(index + 1, error);
        });
      }

      requestNext(0).catch(function (err) {
        console.error('[知视 Main World] 获取字幕失败:', err);
        postCaptionSubtitlesResult({
          requestId: requestId,
          text: '',
          url: urls[0] || '',
          status: 0,
          contentType: '',
          error: err && err.message ? err.message : '获取字幕失败'
        });
      });
    } catch (err) {
      console.error('[知视 Main World] 获取字幕失败:', err);
      postCaptionSubtitlesResult({
        requestId: requestId,
        text: '',
        url: '',
        status: 0,
        contentType: '',
        error: err && err.message ? err.message : '获取字幕失败'
      });
    }
  }

  function handleSeekVideo(time) {
    try {
      if (typeof time !== 'number' || time < 0) {
        console.warn('[知视 Main World] 无效的跳转时间:', time);
        return;
      }

      var playerEl = getPlayerElement();
      if (playerEl && typeof playerEl.seekTo === 'function') {
        // seekTo(seconds, allowSeekAhead)
        playerEl.seekTo(time, true);
        console.log('[知视 Main World] 视频已跳转到:', time, '秒');
      } else {
        console.warn('[知视 Main World] 无法找到播放器或播放器不支持 seekTo');
      }
    } catch (err) {
      console.error('[知视 Main World] 视频跳转失败:', err);
    }
  }

  // ============ 初始化日志 ============

  console.log('[知视 Main World] 脚本已加载，等待消息指令');
})();
