/**
 * subtitle.js - YouTube 字幕与视频元信息获取
 *
 * 全局对象：SubtitleFetcher
 * 负责：
 *   - 解析当前页面视频 ID 与页面类型
 *   - 通过 window.postMessage 与 main-world.js 通信获取字幕轨道
 *   - 请求并解析字幕（JSON3 格式）
 *   - 评估字幕质量
 *
 * 注意：YouTube 页面内部的 ytplayer.config / ytInitialData 等对象存在于页面主世界，
 * content script（隔离世界）无法直接访问，因此需要通过注入的 main-world.js 桥接。
 */

/* global window, fetch, DOMParser */

// 使用全局对象暴露 API（不使用 ES 模块）
window.SubtitleFetcher = (function () {
  'use strict';

  // 与 main-world.js 约定的消息类型
  var MSG_GET_TRACKS = 'KV_GET_CAPTION_TRACKS';
  var MSG_TRACKS_RESULT = 'KV_CAPTION_TRACKS_RESULT';
  var MSG_FETCH_SUBTITLES = 'KV_FETCH_CAPTION_SUBTITLES';
  var MSG_SUBTITLES_RESULT = 'KV_CAPTION_SUBTITLES_RESULT';
  // YouTube 的转写文稿面板可能在视频页稳定后才开始渲染。
  var SUBTITLES_TIMEOUT = 30000;
  // 请求字幕轨道的超时时间（毫秒）
  var TRACKS_TIMEOUT = 35000;

  /**
   * 从当前页面 URL 解析视频 ID
   * 支持两种格式：
   *   - https://www.youtube.com/watch?v=VIDEO_ID
   *   - https://youtu.be/VIDEO_ID
   * @returns {string|null} 视频 ID，解析失败返回 null
   */
  function parseYouTubeUrl(input) {
    try {
      var value = String(input || '').trim();
      if (!value) {
        return null;
      }

      if (/^[a-zA-Z0-9_-]{11}$/.test(value)) {
        return {
          videoId: value,
          url: 'https://www.youtube.com/watch?v=' + value
        };
      }

      if (!/^[a-zA-Z][a-zA-Z\d+.-]*:/.test(value)) {
        value = 'https://' + value;
      }

      var parsedUrl = new URL(value);
      var hostname = parsedUrl.hostname.toLowerCase().replace(/^www\./, '');
      var videoId = '';

      if (hostname === 'youtu.be') {
        videoId = parsedUrl.pathname.split('/').filter(Boolean)[0] || '';
      } else if (
        hostname === 'youtube.com' ||
        hostname.endsWith('.youtube.com') ||
        hostname === 'youtube-nocookie.com' ||
        hostname.endsWith('.youtube-nocookie.com')
      ) {
        if (parsedUrl.pathname === '/watch') {
          videoId = parsedUrl.searchParams.get('v') || '';
        } else {
          var segments = parsedUrl.pathname.split('/').filter(Boolean);
          if (segments[0] === 'shorts' || segments[0] === 'embed' || segments[0] === 'live') {
            videoId = segments[1] || '';
          }
        }
      }

      if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
        return null;
      }

      return {
        videoId: videoId,
        url: 'https://www.youtube.com/watch?v=' + videoId
      };
    } catch (e) {
      return null;
    }
  }

  function getVideoId() {
    var parsed = parseYouTubeUrl(window.location.href);
    return parsed ? parsed.videoId : null;
  }

  /**
   * 判断当前是否在视频观看页面
   * @returns {boolean}
   */
  function isWatchPage() {
    try {
      var path = window.location.pathname;
      var href = window.location.href;
      // /watch 页面或 youtu.be 短链
      return path === '/watch' || href.indexOf('watch?v=') !== -1 || href.indexOf('youtu.be/') !== -1;
    } catch (e) {
      return false;
    }
  }

  /**
   * 通过 window.postMessage 向 main-world.js 请求字幕轨道信息
   * 发送 { type: 'KV_GET_CAPTION_TRACKS' }，等待 { type: 'KV_CAPTION_TRACKS_RESULT', tracks: [...] }
   * 使用 Promise + 超时机制（10 秒）
   * @returns {Promise<Array<Object>>} 字幕轨道数组，每个 track 含：
   *   { baseUrl, languageCode, name, kind, isAutoGenerated }
   */
  function requestCaptionTracks() {
    return new Promise(function (resolve, reject) {
      var timedOut = false;
      var responded = false;

      // 监听来自 main-world.js 的响应
      function onMessage(event) {
        // 仅接受来自当前窗口的消息
        if (event.source !== window) {
          return;
        }
        var data = event.data;
        if (!data || typeof data !== 'object') {
          return;
        }
        if (data.type !== MSG_TRACKS_RESULT) {
          return;
        }
        if (responded || timedOut) {
          return;
        }
        responded = true;
        window.removeEventListener('message', onMessage);
        if (data.error) {
          reject(new Error(data.error));
          return;
        }
        var tracks = Array.isArray(data.tracks) ? data.tracks : [];
        resolve(tracks);
      }

      window.addEventListener('message', onMessage);

      // 发送请求到 main-world.js
      window.postMessage({ type: MSG_GET_TRACKS }, '*');

      // 超时处理
      setTimeout(function () {
        if (responded) {
          return;
        }
        timedOut = true;
        window.removeEventListener('message', onMessage);
        reject(new Error('获取字幕轨道超时：未在 ' + (TRACKS_TIMEOUT / 1000) + ' 秒内收到 main-world.js 的响应，请刷新页面后重试。'));
      }, TRACKS_TIMEOUT);
    });
  }

  /**
   * 解析 JSON3 格式的字幕数据为字幕行数组
   * JSON3 结构：{ events: [ { tStartMs, dDurationMs, segs: [ { utf8 } ], aAppend?, wWinId? } ] }
   * @param {Object} json3 - 解析后的 JSON3 对象
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseJson3(json3) {
    var lines = [];
    if (!json3 || !json3.events || !Array.isArray(json3.events)) {
      return lines;
    }
    for (var i = 0; i < json3.events.length; i++) {
      var ev = json3.events[i];
      // 跳过无 segs 或无起始时间的事件（如样式定义事件）
      if (!ev.segs || typeof ev.tStartMs === 'undefined') {
        continue;
      }
      // 拼接 segs 中的文本
      var text = '';
      for (var j = 0; j < ev.segs.length; j++) {
        if (ev.segs[j] && typeof ev.segs[j].utf8 === 'string') {
          text += ev.segs[j].utf8;
        }
      }
      text = text.replace(/\n/g, ' ').trim();
      // 跳过空文本和仅含换行符的事件
      if (!text) {
        continue;
      }
      // 跳过 YouTube 自动字幕中的换行/样式标记（如 "\n"）
      var start = ev.tStartMs / 1000; // 毫秒转秒
      var dur = ev.dDurationMs ? ev.dDurationMs / 1000 : 0;
      lines.push({
        start: start,
        dur: dur,
        text: text
      });
    }
    return lines;
  }

  /**
   * 请求 track.baseUrl 获取字幕，解析为字幕行数组
   * baseUrl 追加 &fmt=json3 参数获取 JSON 格式
   * @param {Object} track - 字幕轨道对象，需含 baseUrl
   * @returns {Promise<Array<{start:number, dur:number, text:string}>>}
   */
  /**
   * 为字幕请求生成唯一 ID
   * @returns {string}
   */
  function buildRequestId() {
    return 'sub_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2);
  }

  /**
   * 通过 window.postMessage 请求字幕正文
   * @param {Object} track - 字幕轨道
   * @returns {Promise<Object>} 包含 text 的响应对象
   */
  function requestCaptionSubtitles(track) {
    return new Promise(function (resolve, reject) {
      var requestId = buildRequestId();
      var timedOut = false;
      var responded = false;

      function onMessage(event) {
        if (event.source !== window) {
          return;
        }

        var data = event.data;
        if (!data || typeof data !== 'object') {
          return;
        }
        if (data.type !== MSG_SUBTITLES_RESULT || data.requestId !== requestId) {
          return;
        }
        if (responded || timedOut) {
          return;
        }

        responded = true;
        window.removeEventListener('message', onMessage);

        if (data.error) {
          reject(new Error(data.error));
          return;
        }

        resolve(data);
      }

      window.addEventListener('message', onMessage);
      window.postMessage({
        type: MSG_FETCH_SUBTITLES,
        requestId: requestId,
        track: {
          baseUrl: track.baseUrl || "",
          languageCode: track.languageCode || "",
          name: track.name || "",
          kind: track.kind || "",
          isAutoGenerated: !!track.isAutoGenerated,
          vssId: track.vssId || ""
        }
      }, '*');

      setTimeout(function () {
        if (responded) {
          return;
        }
        timedOut = true;
        window.removeEventListener('message', onMessage);
        reject(new Error('获取字幕超时：' + (SUBTITLES_TIMEOUT / 1000) + ' 秒内未收到字幕内容，请刷新视频页后重试'));
      }, SUBTITLES_TIMEOUT);
    });
  }

  /**
   * 解析字幕正文，兼容 JSON3 和 XML
   * @param {string} text
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseSubtitleText(text) {
    var normalized = String(text || '').replace(/^\uFEFF/, '').trim();
    if (!normalized) {
      return [];
    }

    try {
      var json3 = JSON.parse(normalized);
      var jsonLines = parseJson3(json3);
      if (jsonLines.length > 0) {
        return jsonLines;
      }
    } catch (e) {
      // JSON3 解析失败时继续尝试 XML
    }

    var xmlLines = parseXML(normalized);
    if (xmlLines.length > 0) {
      return xmlLines;
    }

    return parseWebVtt(normalized);
  }

  /**
   * 解析 WebVTT 字幕格式。
   * @param {string} text
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseWebVtt(text) {
    var lines = [];
    var blocks = String(text || '').replace(/\r/g, '').split(/\n\s*\n/);
    for (var blockIndex = 0; blockIndex < blocks.length; blockIndex++) {
      var blockLines = blocks[blockIndex].split('\n').map(function (line) {
        return line.trim();
      }).filter(Boolean);
      var timeIndex = -1;
      for (var lineIndex = 0; lineIndex < blockLines.length; lineIndex++) {
        if (blockLines[lineIndex].indexOf('-->') !== -1) {
          timeIndex = lineIndex;
          break;
        }
      }
      if (timeIndex === -1) {
        continue;
      }

      var timestamps = blockLines[timeIndex].split('-->');
      var start = parseTimeAttr(timestamps[0]);
      var end = parseTimeAttr((timestamps[1] || '').split(' ')[0]);
      var cueText = blockLines.slice(timeIndex + 1).join(' ').replace(/<[^>]+>/g, '').trim();
      if (cueText) {
        lines.push({ start: start, dur: end > start ? end - start : 0, text: cueText });
      }
    }
    return lines;
  }

  /**
   * 获取并解析字幕正文
   * @param {Object} track - 含 baseUrl 的字幕轨道
   * @returns {Promise<Array<{start:number, dur:number, text:string}>>}
   */
  function fetchSubtitles(track) {
    var transcriptPromise = requestTranscriptPanelSubtitles().then(function (lines) {
      if (!lines || lines.length === 0) {
        throw new Error('转写文稿为空');
      }
      return lines;
    });

    var captionPromise = null;
    if (track && track.baseUrl) {
      captionPromise = requestCaptionSubtitles(track).then(function (payload) {
        var lines = parseSubtitleText(payload.text || '');
        if (lines.length === 0) {
          throw new Error('字幕接口返回空内容');
        }
        return lines;
      });
    }

    return new Promise(function (resolve, reject) {
      var pending = captionPromise ? 2 : 1;
      var errors = [];
      var settled = false;

      function handleSuccess(lines) {
        if (settled) {
          return;
        }
        settled = true;
        resolve(lines);
      }

      function handleFailure(error) {
        errors.push(error);
        pending--;
        if (pending === 0 && !settled) {
          settled = true;
          reject(new Error('字幕读取失败：' + errors.map(function (item) {
            return item && item.message ? item.message : '未知错误';
          }).join('；')));
        }
      }

      transcriptPromise.then(handleSuccess, handleFailure);
      if (captionPromise) {
        captionPromise.then(handleSuccess, handleFailure);
      }
    });
  }


  /**
   * 判断文本是否像字幕时间戳，例如 0:01 / 1:02 / 1:02:03
   * @param {string} text
   * @returns {boolean}
   */
  function looksLikeTranscriptTimestamp(text) {
    if (!text) {
      return false;
    }
    return /^\d{1,2}:\d{2}(?::\d{2})?(?:\.\d+)?$/.test(String(text).trim());
  }

  /**
   * 判断文本是否像时长辅助标签，例如“1秒钟”或“1分钟9秒钟”
   * @param {string} text
   * @returns {boolean}
   */
  function looksLikeTranscriptDurationLabel(text) {
    if (!text) {
      return false;
    }
    return /\d+\s*(秒钟?|分钟|小时|second|seconds|minute|minutes|hour|hours|sec|secs|min|mins)/i.test(String(text).trim());
  }

  /**
   * 查找“内容转文字”按钮
   * @returns {HTMLElement|null}
   */
  function findTranscriptButton() {
    try {
      var transcriptSection = document.querySelector('ytd-video-description-transcript-section-renderer');
      if (transcriptSection) {
        var sectionButtons = transcriptSection.querySelectorAll('button');
        if (sectionButtons && sectionButtons.length > 0) {
          return sectionButtons[0];
        }

        var sectionFallback = transcriptSection.querySelector('ytd-button-renderer button, tp-yt-paper-button button, button');
        if (sectionFallback) {
          return sectionFallback;
        }
      }

      var allButtons = Array.from(document.querySelectorAll('button, ytd-button-renderer, tp-yt-paper-button'));
      var transcriptKeywords = ['内容转文字', '转写', '转文字', '文字记录', 'transcript', 'transcription', 'show transcript'];

      for (var buttonIndex = 0; buttonIndex < allButtons.length; buttonIndex++) {
        var button = allButtons[buttonIndex];
        var labelText = [
          button.getAttribute ? button.getAttribute('aria-label') || '' : '',
          button.getAttribute ? button.getAttribute('title') || '' : '',
          button.textContent || ''
        ].join(' ').toLowerCase();

        for (var keywordIndex = 0; keywordIndex < transcriptKeywords.length; keywordIndex++) {
          if (labelText.indexOf(transcriptKeywords[keywordIndex].toLowerCase()) !== -1) {
            return button;
          }
        }
      }
    } catch (error) {
      // 忽略查找失败，交给上层处理
    }

    return null;
  }

  /**
   * 等待 YouTube 延迟渲染“内容转文字”按钮。
   * @param {number} timeoutMs
   * @returns {Promise<HTMLElement>}
   */
  function waitForTranscriptButton(timeoutMs) {
    var deadline = Date.now() + (timeoutMs || SUBTITLES_TIMEOUT);

    return new Promise(function (resolve, reject) {
      function check() {
        var button = findTranscriptButton();
        if (button) {
          resolve(button);
          return;
        }

        if (Date.now() >= deadline) {
          reject(new Error('获取转写文稿失败：等待“内容转文字”按钮超时'));
          return;
        }

        setTimeout(check, 250);
      }

      check();
    });
  }

  /**
   * 获取当前页面上的转写文稿面板
   * @returns {HTMLElement|null}
   */
  function getTranscriptPanel() {
    try {
      var panel = document.querySelector(
        'ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"], ' +
        'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"]'
      );

      if (panel && panel.querySelector('transcript-segment-view-model, ytd-transcript-segment-renderer')) {
        return panel;
      }

      var firstSegment = document.querySelector('transcript-segment-view-model, ytd-transcript-segment-renderer');
      if (!firstSegment) {
        return panel;
      }

      return firstSegment.closest(
        'ytd-engagement-panel-section-list-renderer, ' +
        'ytd-transcript-search-panel-renderer, ' +
        'ytd-transcript-renderer'
      ) || document;
    } catch (error) {
      return null;
    }
  }

  function closeTranscriptPanel(panel) {
    if (!panel || !panel.querySelector) {
      return;
    }

    var closeButton = panel.querySelector(
      'button[aria-label*="关闭"], ' +
      'button[aria-label*="Close"], ' +
      '#visibility-button button, ' +
      'yt-icon-button#visibility-button'
    );
    if (closeButton && typeof closeButton.click === 'function') {
      closeButton.click();
    }
  }

  /**
   * 等待转写文稿面板加载完成
   * @param {number} timeoutMs
   * @returns {Promise<HTMLElement>}
   */
  function waitForTranscriptPanel(timeoutMs) {
    var deadline = Date.now() + (timeoutMs || SUBTITLES_TIMEOUT);

    return new Promise(function (resolve, reject) {
      function check() {
        var panel = getTranscriptPanel();
        if (panel) {
          var segmentCount = panel.querySelectorAll('transcript-segment-view-model, ytd-transcript-segment-renderer').length;
          if (segmentCount > 0) {
            resolve(panel);
            return;
          }
        }

        if (Date.now() >= deadline) {
          reject(new Error('获取转写文稿失败：等待面板加载超时'));
          return;
        }

        setTimeout(check, 250);
      }

      check();
    });
  }

  /**
   * 从转写文稿条目中提取时间戳
   * @param {HTMLElement} segmentNode
   * @returns {number}
   */
  function extractTranscriptSegmentStart(segmentNode) {
    if (!segmentNode) {
      return 0;
    }

    var timestampNode = segmentNode.querySelector('.ytwTranscriptSegmentViewModelTimestamp, [aria-hidden="true"]');
    var timestampText = timestampNode ? String(timestampNode.textContent || '').trim() : '';

    if (!timestampText) {
      var fallbackLines = String(segmentNode.innerText || segmentNode.textContent || '')
        .split(/\n+/)
        .map(function (line) { return line.trim(); })
        .filter(Boolean);
      timestampText = fallbackLines.length > 0 ? fallbackLines[0] : '';
    }

    return parseTimeAttr(timestampText);
  }

  /**
   * 从转写文稿条目中提取正文文本
   * @param {HTMLElement} segmentNode
   * @returns {string}
   */
  function extractTranscriptSegmentText(segmentNode) {
    if (!segmentNode) {
      return '';
    }

    var contentParts = [];
    var childElements = segmentNode.children ? Array.from(segmentNode.children) : [];

    for (var childIndex = 0; childIndex < childElements.length; childIndex++) {
      var childElement = childElements[childIndex];
      var className = typeof childElement.className === 'string' ? childElement.className : '';

      if (className.indexOf('Timestamp') !== -1 || className.indexOf('timestamp') !== -1) {
        continue;
      }

      var childText = String(childElement.innerText || childElement.textContent || '').trim();
      if (childText) {
        contentParts.push(childText);
      }
    }

    if (contentParts.length === 0) {
      var fallbackLines = String(segmentNode.innerText || segmentNode.textContent || '')
        .split(/\n+/)
        .map(function (line) { return line.trim(); })
        .filter(Boolean);

      if (fallbackLines.length > 0 && looksLikeTranscriptTimestamp(fallbackLines[0])) {
        fallbackLines.shift();
      }

      if (fallbackLines.length > 0 && looksLikeTranscriptDurationLabel(fallbackLines[0])) {
        fallbackLines.shift();
      }

      contentParts = fallbackLines;
    }

    return contentParts.join(' ').replace(/\s+/g, ' ').trim();
  }

  /**
   * 从转写文稿面板提取字幕行
   * @param {HTMLElement} panel
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function extractTranscriptLinesFromPanel(panel) {
    var lines = [];
    if (!panel) {
      return lines;
    }

    var segmentNodes = Array.from(panel.querySelectorAll('transcript-segment-view-model, ytd-transcript-segment-renderer'));
    for (var segmentIndex = 0; segmentIndex < segmentNodes.length; segmentIndex++) {
      var segmentNode = segmentNodes[segmentIndex];
      var segmentText = extractTranscriptSegmentText(segmentNode);
      if (!segmentText) {
        continue;
      }

      lines.push({
        start: extractTranscriptSegmentStart(segmentNode),
        dur: 0,
        text: segmentText
      });
    }

    if (lines.length > 1) {
      for (var lineIndex = 0; lineIndex < lines.length - 1; lineIndex++) {
        var currentLine = lines[lineIndex];
        var nextLine = lines[lineIndex + 1];
        var duration = (nextLine.start || 0) - (currentLine.start || 0);
        currentLine.dur = duration > 0 ? duration : 0;
      }
    }

    return lines;
  }

  /**
   * 从面板 innerText 中解析字幕行，作为结构变化时的后备方案
   * @param {string} panelText
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseTranscriptPanelText(panelText) {
    var lines = [];
    var normalizedText = String(panelText || '').replace(/\r/g, '\n');

    if (!normalizedText.trim()) {
      return lines;
    }

    var rawLines = normalizedText.split(/\n+/).map(function (line) {
      return line.trim();
    }).filter(Boolean);

    var currentStart = null;
    var currentTextParts = [];

    function flushCurrentLine(nextStart) {
      if (currentStart === null || currentTextParts.length === 0) {
        currentTextParts = [];
        currentStart = nextStart;
        return;
      }

      lines.push({
        start: currentStart,
        dur: typeof nextStart === 'number' && nextStart > currentStart ? nextStart - currentStart : 0,
        text: currentTextParts.join(' ').replace(/\s+/g, ' ').trim()
      });

      currentTextParts = [];
      currentStart = nextStart;
    }

    for (var rawIndex = 0; rawIndex < rawLines.length; rawIndex++) {
      var rawLine = rawLines[rawIndex];

      if (looksLikeTranscriptTimestamp(rawLine)) {
        flushCurrentLine(parseTimeAttr(rawLine));
        if (currentStart === null) {
          currentStart = parseTimeAttr(rawLine);
        }
        continue;
      }

      if (looksLikeTranscriptDurationLabel(rawLine)) {
        continue;
      }

      if (currentStart !== null) {
        currentTextParts.push(rawLine);
      }
    }

    if (currentStart !== null && currentTextParts.length > 0) {
      lines.push({
        start: currentStart,
        dur: 0,
        text: currentTextParts.join(' ').replace(/\s+/g, ' ').trim()
      });
    }

    return lines;
  }

  /**
   * 打开转写文稿面板并提取字幕
   * @returns {Promise<Array<{start:number, dur:number, text:string}>>}
   */
  function requestTranscriptPanelSubtitles() {
    return new Promise(function (resolve, reject) {
      var openedByExtension = false;
      var existingPanel = getTranscriptPanel();
      if (existingPanel) {
        var existingLines = extractTranscriptLinesFromPanel(existingPanel);
        if (existingLines.length > 0) {
          resolve(existingLines);
          return;
        }
      }

      waitForTranscriptButton(SUBTITLES_TIMEOUT).then(function (transcriptButton) {
        try {
          if (typeof transcriptButton.scrollIntoView === 'function') {
            transcriptButton.scrollIntoView({ block: 'center' });
          }
          transcriptButton.click();
          openedByExtension = true;
        } catch (error) {
          throw new Error('获取转写文稿失败：无法点击“内容转文字”按钮');
        }

        return waitForTranscriptPanel(SUBTITLES_TIMEOUT);
      }).then(function (panel) {
        var lines = extractTranscriptLinesFromPanel(panel);
        if (lines.length > 0) {
          if (openedByExtension) {
            closeTranscriptPanel(panel);
          }
          resolve(lines);
          return;
        }

        var fallbackLines = parseTranscriptPanelText(panel.innerText || panel.textContent || '');
        if (fallbackLines.length > 0) {
          if (openedByExtension) {
            closeTranscriptPanel(panel);
          }
          resolve(fallbackLines);
          return;
        }

        if (openedByExtension) {
          closeTranscriptPanel(panel);
        }
        reject(new Error('获取转写文稿失败：面板已打开但未提取到字幕内容'));
      }).catch(function (error) {
        reject(error);
      });
    });
  }


  function parseXML(xmlText) {
    var lines = [];
    try {
      var parser = new DOMParser();
      var doc = parser.parseFromString(xmlText, 'text/xml');
      if (!doc) {
        return lines;
      }
      // 标准 TTML: <p begin="..." dur="...">text</p>
      var ps = doc.getElementsByTagName('p');
      for (var i = 0; i < ps.length; i++) {
        var p = ps[i];
        var begin = p.getAttribute('begin');
        var dur = p.getAttribute('dur');
        var text = (p.textContent || '').replace(/\n/g, ' ').trim();
        if (!text) {
          continue;
        }
        var startSec = parseTimeAttr(begin);
        var durSec = parseTimeAttr(dur);
        lines.push({ start: startSec, dur: durSec, text: text });
      }
      // 如果 TTML 没有解析到，尝试 YouTube 旧版 <text start="..." dur="..."> 格式
      if (lines.length === 0) {
        var texts = doc.getElementsByTagName('text');
        for (var j = 0; j < texts.length; j++) {
          var t = texts[j];
          var s = parseFloat(t.getAttribute('start')) || 0;
          var d = parseFloat(t.getAttribute('dur')) || 0;
          var txt = (t.textContent || '').replace(/\n/g, ' ').trim();
          // 解码 HTML 实体（textContent 已自动解码）
          if (txt) {
            lines.push({ start: s, dur: d, text: txt });
          }
        }
      }
    } catch (e) {
      // 解析失败，返回空数组
    }
    return lines;
  }

  /**
   * 解析 TTML 时间属性（如 "00:01:23.456" 或 "12.5s" 或 "12.5"）
   * @param {string} attr
   * @returns {number} 秒数
   */
  function parseTimeAttr(attr) {
    if (!attr) {
      return 0;
    }
    attr = String(attr).trim();
    // 末尾带 s（如 "12.5s"）
    if (attr.charAt(attr.length - 1) === 's') {
      var num = parseFloat(attr);
      if (!isNaN(num)) {
        return num;
      }
    }
    // HH:MM:SS.fff 格式
    var m = attr.match(/^(\d+):(\d{2}):(\d{2}(?:\.\d+)?)$/);
    if (m) {
      return parseInt(m[1], 10) * 3600 + parseInt(m[2], 10) * 60 + parseFloat(m[3]);
    }
    // MM:SS.fff 格式
    m = attr.match(/^(\d+):(\d{2}(?:\.\d+)?)$/);
    if (m) {
      return parseInt(m[1], 10) * 60 + parseFloat(m[2]);
    }
    // 纯数字（秒）
    var n = parseFloat(attr);
    return isNaN(n) ? 0 : n;
  }

  /**
   * 评估字幕质量
   * 检查项：文本完整度（空行比例）、标点规范度、ASR 错误启发式（重复词、无标点等）
   * @param {Array<{start:number, dur:number, text:string}>} subtitleLines - 字幕行数组
   * @returns {{level:'good'|'fair'|'poor', score:number}} 质量评级与分数（0-100）
   */
  function assessQuality(subtitleLines) {
    if (!Array.isArray(subtitleLines) || subtitleLines.length === 0) {
      return { level: 'poor', score: 0 };
    }

    var totalLines = subtitleLines.length;
    var emptyLines = 0;          // 空行数
    var noPunctLines = 0;        // 无标点行数
    var repeatWordHits = 0;      // 存在重复词的行数
    var totalWords = 0;          // 总词数（用于计算平均句长）
    var totalChars = 0;          // 总字符数

    // 常见 ASR 错误模式：连续重复词（如 "the the", "is is"）
    var repeatRegex = /\b(\w+)\s+\1\b/i;
    // 标点符号集合（中英文）
    var punctRegex = /[。，、；：！？.,;:!?]/;

    for (var i = 0; i < subtitleLines.length; i++) {
      var line = subtitleLines[i];
      var text = (line && line.text) ? String(line.text).trim() : '';

      if (!text) {
        emptyLines++;
        continue;
      }

      totalChars += text.length;
      var words = text.split(/\s+/).filter(Boolean);
      totalWords += words.length;

      // 检查标点规范度：完全没有标点的行视为不规范
      if (!punctRegex.test(text)) {
        noPunctLines++;
      }

      // 检查 ASR 重复词模式
      if (repeatRegex.test(text)) {
        repeatWordHits++;
      }
    }

    var nonEmptyLines = totalLines - emptyLines;
    if (nonEmptyLines === 0) {
      return { level: 'poor', score: 0 };
    }

    // 各维度占比（0-1）
    var emptyRatio = emptyLines / totalLines;            // 空行比例（越低越好）
    var noPunctRatio = noPunctLines / nonEmptyLines;     // 无标点比例（越低越好）
    var repeatRatio = repeatWordHits / nonEmptyLines;    // 重复词比例（越低越好）
    var avgWordsPerLine = totalWords / nonEmptyLines;    // 平均每行词数

    // 计算分数（满分 100）
    var score = 100;

    // 文本完整度：空行越多扣分越多（空行比例 * 30 分）
    score -= emptyRatio * 30;

    // 标点规范度：无标点行越多扣分越多（无标点比例 * 25 分）
    // 注意：自动字幕通常无标点，这是判断 ASR 的重要依据
    score -= noPunctRatio * 25;

    // ASR 重复词：重复越多扣分越多（重复比例 * 20 分）
    score -= repeatRatio * 20;

    // 平均句长过短（碎片化）扣分：每行平均词数 < 3 视为碎片化
    if (avgWordsPerLine < 3) {
      score -= (3 - avgWordsPerLine) * 10;
    }

    // 限制在 0-100
    score = Math.max(0, Math.min(100, Math.round(score)));

    // 根据分数评级
    var level;
    if (score >= 75) {
      level = 'good';
    } else if (score >= 50) {
      level = 'fair';
    } else {
      level = 'poor';
    }

    return { level: level, score: score };
  }

  /**
   * 将字幕行数组转为纯文本（合并所有 text，按句分割）
   * @param {Array<{start:number, dur:number, text:string}>} lines - 字幕行数组
   * @returns {string} 纯文本
   */
  function subtitlesToText(lines) {
    if (!Array.isArray(lines) || lines.length === 0) {
      return '';
    }
    // 合并所有文本
    var merged = [];
    for (var i = 0; i < lines.length; i++) {
      var text = (lines[i] && lines[i].text) ? String(lines[i].text).trim() : '';
      if (text) {
        merged.push(text);
      }
    }
    var raw = merged.join(' ');
    // 规范化空白
    raw = raw.replace(/\s+/g, ' ').trim();
    // 按句分割后重新拼接为带换行的文本，便于阅读
    // 句子结束标志：. ! ? 后跟空格或结尾
    var sentences = raw.match(/[^.!?]+[.!?]*(?:\s|$)/g);
    if (!sentences) {
      return raw;
    }
    return sentences.map(function (s) {
      return s.trim();
    }).filter(Boolean).join('\n');
  }

  return {
    parseYouTubeUrl: parseYouTubeUrl,
    parseSubtitleText: parseSubtitleText,
    getVideoId: getVideoId,
    isWatchPage: isWatchPage,
    requestCaptionTracks: requestCaptionTracks,
    fetchSubtitles: fetchSubtitles,
    assessQuality: assessQuality,
    subtitlesToText: subtitlesToText
  };
})();
