/**
 * subtitle.js - YouTube 字幕与视频元信息获取
 *
 * 全局对象：SubtitleFetcher
 * 负责：
 *   - 解析当前页面视频 ID 与页面类型
 *   - 通过 window.postMessage 与 main-world.js 通信获取字幕轨道
 *   - 请求并解析字幕（JSON3 格式）
 *   - 评估字幕质量
 *
 * 注意：YouTube 页面内部的 ytplayer.config / ytInitialData 等对象存在于页面主世界，
 * content script（隔离世界）无法直接访问，因此需要通过注入的 main-world.js 桥接。
 */

/* global window, fetch, DOMParser */

// 使用全局对象暴露 API（不使用 ES 模块）
window.SubtitleFetcher = (function () {
  'use strict';

  // 与 main-world.js 约定的消息类型
  var MSG_GET_TRACKS = 'KV_GET_CAPTION_TRACKS';
  var MSG_TRACKS_RESULT = 'KV_CAPTION_TRACKS_RESULT';
  // 请求字幕轨道的超时时间（毫秒）
  var TRACKS_TIMEOUT = 10000;

  /**
   * 从当前页面 URL 解析视频 ID
   * 支持两种格式：
   *   - https://www.youtube.com/watch?v=VIDEO_ID
   *   - https://youtu.be/VIDEO_ID
   * @returns {string|null} 视频 ID，解析失败返回 null
   */
  function getVideoId() {
    try {
      var url = window.location.href;
      // watch?v=xxx 格式
      var match = url.match(/[?&]v=([a-zA-Z0-9_-]{11})/);
      if (match) {
        return match[1];
      }
      // youtu.be/xxx 格式
      match = url.match(/youtu\.be\/([a-zA-Z0-9_-]{11})/);
      if (match) {
        return match[1];
      }
      // embed/xxx 格式
      match = url.match(/youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/);
      if (match) {
        return match[1];
      }
      return null;
    } catch (e) {
      return null;
    }
  }

  /**
   * 判断当前是否在视频观看页面
   * @returns {boolean}
   */
  function isWatchPage() {
    try {
      var path = window.location.pathname;
      var href = window.location.href;
      // /watch 页面或 youtu.be 短链
      return path === '/watch' || href.indexOf('watch?v=') !== -1 || href.indexOf('youtu.be/') !== -1;
    } catch (e) {
      return false;
    }
  }

  /**
   * 通过 window.postMessage 向 main-world.js 请求字幕轨道信息
   * 发送 { type: 'KV_GET_CAPTION_TRACKS' }，等待 { type: 'KV_CAPTION_TRACKS_RESULT', tracks: [...] }
   * 使用 Promise + 超时机制（10 秒）
   * @returns {Promise<Array<Object>>} 字幕轨道数组，每个 track 含：
   *   { baseUrl, languageCode, name, kind, isAutoGenerated }
   */
  function requestCaptionTracks() {
    return new Promise(function (resolve, reject) {
      var timedOut = false;
      var responded = false;

      // 监听来自 main-world.js 的响应
      function onMessage(event) {
        // 仅接受来自当前窗口的消息
        if (event.source !== window) {
          return;
        }
        var data = event.data;
        if (!data || typeof data !== 'object') {
          return;
        }
        if (data.type !== MSG_TRACKS_RESULT) {
          return;
        }
        if (responded || timedOut) {
          return;
        }
        responded = true;
        window.removeEventListener('message', onMessage);
        var tracks = Array.isArray(data.tracks) ? data.tracks : [];
        resolve(tracks);
      }

      window.addEventListener('message', onMessage);

      // 发送请求到 main-world.js
      window.postMessage({ type: MSG_GET_TRACKS }, '*');

      // 超时处理
      setTimeout(function () {
        if (responded) {
          return;
        }
        timedOut = true;
        window.removeEventListener('message', onMessage);
        reject(new Error('获取字幕轨道超时：未在 ' + (TRACKS_TIMEOUT / 1000) + ' 秒内收到 main-world.js 的响应，请刷新页面后重试。'));
      }, TRACKS_TIMEOUT);
    });
  }

  /**
   * 解析 JSON3 格式的字幕数据为字幕行数组
   * JSON3 结构：{ events: [ { tStartMs, dDurationMs, segs: [ { utf8 } ], aAppend?, wWinId? } ] }
   * @param {Object} json3 - 解析后的 JSON3 对象
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseJson3(json3) {
    var lines = [];
    if (!json3 || !json3.events || !Array.isArray(json3.events)) {
      return lines;
    }
    for (var i = 0; i < json3.events.length; i++) {
      var ev = json3.events[i];
      // 跳过无 segs 或无起始时间的事件（如样式定义事件）
      if (!ev.segs || typeof ev.tStartMs === 'undefined') {
        continue;
      }
      // 拼接 segs 中的文本
      var text = '';
      for (var j = 0; j < ev.segs.length; j++) {
        if (ev.segs[j] && typeof ev.segs[j].utf8 === 'string') {
          text += ev.segs[j].utf8;
        }
      }
      text = text.replace(/\n/g, ' ').trim();
      // 跳过空文本和仅含换行符的事件
      if (!text) {
        continue;
      }
      // 跳过 YouTube 自动字幕中的换行/样式标记（如 "\n"）
      var start = ev.tStartMs / 1000; // 毫秒转秒
      var dur = ev.dDurationMs ? ev.dDurationMs / 1000 : 0;
      lines.push({
        start: start,
        dur: dur,
        text: text
      });
    }
    return lines;
  }

  /**
   * 请求 track.baseUrl 获取字幕，解析为字幕行数组
   * baseUrl 追加 &fmt=json3 参数获取 JSON 格式
   * @param {Object} track - 字幕轨道对象，需含 baseUrl
   * @returns {Promise<Array<{start:number, dur:number, text:string}>>}
   */
  function fetchSubtitles(track) {
    if (!track || !track.baseUrl) {
      return Promise.reject(new Error('获取字幕失败：track 或 track.baseUrl 缺失'));
    }
    var url = track.baseUrl;
    // 追加 fmt=json3 以获取 JSON 格式（避免默认的 XML）
    // baseUrl 本身可能已含查询参数，用 & 拼接
    url += (url.indexOf('?') !== -1 ? '&' : '?') + 'fmt=json3';

    return fetch(url, {
      method: 'GET',
      credentials: 'omit' // 字幕请求无需携带 cookie
    }).then(function (resp) {
      if (!resp.ok) {
        throw new Error('获取字幕失败（HTTP ' + resp.status + '）：无法下载字幕数据');
      }
      return resp.text();
    }).then(function (text) {
      if (!text) {
        throw new Error('获取字幕失败：返回内容为空');
      }
      // 优先按 JSON3 解析
      try {
        var json3 = JSON.parse(text);
        var lines = parseJson3(json3);
        if (lines.length > 0) {
          return lines;
        }
      } catch (e) {
        // 非 JSON，可能是 XML 格式，降级解析 XML
      }
      // 降级：尝试按 XML 格式解析
      var xmlLines = parseXML(text);
      if (xmlLines.length > 0) {
        return xmlLines;
      }
      throw new Error('获取字幕失败：无法解析字幕内容（既非 JSON3 也非 XML）');
    });
  }

  /**
   * 降级解析：将字幕 XML（TTML/YouTube XML）解析为字幕行数组
   * @param {string} xmlText - XML 文本
   * @returns {Array<{start:number, dur:number, text:string}>}
   */
  function parseXML(xmlText) {
    var lines = [];
    try {
      var parser = new DOMParser();
      var doc = parser.parseFromString(xmlText, 'text/xml');
      if (!doc) {
        return lines;
      }
      // 标准 TTML: <p begin="..." dur="...">text</p>
      var ps = doc.getElementsByTagName('p');
      for (var i = 0; i < ps.length; i++) {
        var p = ps[i];
        var begin = p.getAttribute('begin');
        var dur = p.getAttribute('dur');
        var text = (p.textContent || '').replace(/\n/g, ' ').trim();
        if (!text) {
          continue;
        }
        var startSec = parseTimeAttr(begin);
        var durSec = parseTimeAttr(dur);
        lines.push({ start: startSec, dur: durSec, text: text });
      }
      // 如果 TTML 没有解析到，尝试 YouTube 旧版 <text start="..." dur="..."> 格式
      if (lines.length === 0) {
        var texts = doc.getElementsByTagName('text');
        for (var j = 0; j < texts.length; j++) {
          var t = texts[j];
          var s = parseFloat(t.getAttribute('start')) || 0;
          var d = parseFloat(t.getAttribute('dur')) || 0;
          var txt = (t.textContent || '').replace(/\n/g, ' ').trim();
          // 解码 HTML 实体（textContent 已自动解码）
          if (txt) {
            lines.push({ start: s, dur: d, text: txt });
          }
        }
      }
    } catch (e) {
      // 解析失败，返回空数组
    }
    return lines;
  }

  /**
   * 解析 TTML 时间属性（如 "00:01:23.456" 或 "12.5s" 或 "12.5"）
   * @param {string} attr
   * @returns {number} 秒数
   */
  function parseTimeAttr(attr) {
    if (!attr) {
      return 0;
    }
    attr = String(attr).trim();
    // 末尾带 s（如 "12.5s"）
    if (attr.charAt(attr.length - 1) === 's') {
      var num = parseFloat(attr);
      if (!isNaN(num)) {
        return num;
      }
    }
    // HH:MM:SS.fff 格式
    var m = attr.match(/^(\d+):(\d{2}):(\d{2}(?:\.\d+)?)$/);
    if (m) {
      return parseInt(m[1], 10) * 3600 + parseInt(m[2], 10) * 60 + parseFloat(m[3]);
    }
    // MM:SS.fff 格式
    m = attr.match(/^(\d+):(\d{2}(?:\.\d+)?)$/);
    if (m) {
      return parseInt(m[1], 10) * 60 + parseFloat(m[2]);
    }
    // 纯数字（秒）
    var n = parseFloat(attr);
    return isNaN(n) ? 0 : n;
  }

  /**
   * 评估字幕质量
   * 检查项：文本完整度（空行比例）、标点规范度、ASR 错误启发式（重复词、无标点等）
   * @param {Array<{start:number, dur:number, text:string}>} subtitleLines - 字幕行数组
   * @returns {{level:'good'|'fair'|'poor', score:number}} 质量评级与分数（0-100）
   */
  function assessQuality(subtitleLines) {
    if (!Array.isArray(subtitleLines) || subtitleLines.length === 0) {
      return { level: 'poor', score: 0 };
    }

    var totalLines = subtitleLines.length;
    var emptyLines = 0;          // 空行数
    var noPunctLines = 0;        // 无标点行数
    var repeatWordHits = 0;      // 存在重复词的行数
    var totalWords = 0;          // 总词数（用于计算平均句长）
    var totalChars = 0;          // 总字符数

    // 常见 ASR 错误模式：连续重复词（如 "the the", "is is"）
    var repeatRegex = /\b(\w+)\s+\1\b/i;
    // 标点符号集合（中英文）
    var punctRegex = /[。，、；：！？.,;:!?]/;

    for (var i = 0; i < subtitleLines.length; i++) {
      var line = subtitleLines[i];
      var text = (line && line.text) ? String(line.text).trim() : '';

      if (!text) {
        emptyLines++;
        continue;
      }

      totalChars += text.length;
      var words = text.split(/\s+/).filter(Boolean);
      totalWords += words.length;

      // 检查标点规范度：完全没有标点的行视为不规范
      if (!punctRegex.test(text)) {
        noPunctLines++;
      }

      // 检查 ASR 重复词模式
      if (repeatRegex.test(text)) {
        repeatWordHits++;
      }
    }

    var nonEmptyLines = totalLines - emptyLines;
    if (nonEmptyLines === 0) {
      return { level: 'poor', score: 0 };
    }

    // 各维度占比（0-1）
    var emptyRatio = emptyLines / totalLines;            // 空行比例（越低越好）
    var noPunctRatio = noPunctLines / nonEmptyLines;     // 无标点比例（越低越好）
    var repeatRatio = repeatWordHits / nonEmptyLines;    // 重复词比例（越低越好）
    var avgWordsPerLine = totalWords / nonEmptyLines;    // 平均每行词数

    // 计算分数（满分 100）
    var score = 100;

    // 文本完整度：空行越多扣分越多（空行比例 * 30 分）
    score -= emptyRatio * 30;

    // 标点规范度：无标点行越多扣分越多（无标点比例 * 25 分）
    // 注意：自动字幕通常无标点，这是判断 ASR 的重要依据
    score -= noPunctRatio * 25;

    // ASR 重复词：重复越多扣分越多（重复比例 * 20 分）
    score -= repeatRatio * 20;

    // 平均句长过短（碎片化）扣分：每行平均词数 < 3 视为碎片化
    if (avgWordsPerLine < 3) {
      score -= (3 - avgWordsPerLine) * 10;
    }

    // 限制在 0-100
    score = Math.max(0, Math.min(100, Math.round(score)));

    // 根据分数评级
    var level;
    if (score >= 75) {
      level = 'good';
    } else if (score >= 50) {
      level = 'fair';
    } else {
      level = 'poor';
    }

    return { level: level, score: score };
  }

  /**
   * 将字幕行数组转为纯文本（合并所有 text，按句分割）
   * @param {Array<{start:number, dur:number, text:string}>} lines - 字幕行数组
   * @returns {string} 纯文本
   */
  function subtitlesToText(lines) {
    if (!Array.isArray(lines) || lines.length === 0) {
      return '';
    }
    // 合并所有文本
    var merged = [];
    for (var i = 0; i < lines.length; i++) {
      var text = (lines[i] && lines[i].text) ? String(lines[i].text).trim() : '';
      if (text) {
        merged.push(text);
      }
    }
    var raw = merged.join(' ');
    // 规范化空白
    raw = raw.replace(/\s+/g, ' ').trim();
    // 按句分割后重新拼接为带换行的文本，便于阅读
    // 句子结束标志：. ! ? 后跟空格或结尾
    var sentences = raw.match(/[^.!?]+[.!?]*(?:\s|$)/g);
    if (!sentences) {
      return raw;
    }
    return sentences.map(function (s) {
      return s.trim();
    }).filter(Boolean).join('\n');
  }

  return {
    getVideoId: getVideoId,
    isWatchPage: isWatchPage,
    requestCaptionTracks: requestCaptionTracks,
    fetchSubtitles: fetchSubtitles,
    assessQuality: assessQuality,
    subtitlesToText: subtitlesToText
  };
})();
